### ISSUE TITLE
还是编译不过去

### ISSUE THREAD

**Issue by chenyunecjtu** [glumes/Vulkan-GPUImage#2]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
错误: 找不到或无法加载主类 io.cdep.bootstrap.Bootstrap
原因: java.lang.ClassNotFoundException: io.cdep.bootstrap.Bootstrap

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/chenyun/projects/github/Vulkan-GPUImage/app/build.gradle' line: 65

**Comment by MemetGhini** [comment]
1.Open a terminal window and navigate to the directory where your project is located.
2.Enter the following commands:
```
$ git clone https://github.com/jomof/cdep-redist.git  
$ cd my-project
$ ../cdep-redist/cdep wrapper
```
3.run yor android project ,it will work

**Comment by MRYangY** [comment]
> 1.Open a terminal window and navigate to the directory where your project is located. 2.Enter the following commands:
> 
> ```
> $ git clone https://github.com/jomof/cdep-redist.git  
> $ cd my-project
> $ ../cdep-redist/cdep wrapper
> ```
> 
> 3.run yor android project ,it will work


An error occurred

-------------------------
Exception in thread "main" java.io.FileNotFoundException: https://raw.githubusercontent.com/jomof/cdep/master/boot.yml
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at io.cdep.bootstrap.WebUtils.getUrlAsString(WebUtils.java:25)
        at io.cdep.bootstrap.Bootstrap.handleMonkeyParse(Bootstrap.java:84)
        at io.cdep.bootstrap.Bootstrap.go(Bootstrap.java:40)
        at io.cdep.bootstrap.Bootstrap.main(Bootstrap.java:34)
